import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";


const todoLists: { id: number, name: string, todos: string[], createdAt: string }[] = [
  { id: 1, name: "Grocery", todos: ["Go for a walk", "Buy Some carrots"], createdAt: "1-3-2022" },
  { id: 2, name: "University", todos: ["Go for laptop repairing"], createdAt: "1-4-2022" },
  { id: 3, name: "Personal", todos: ["Go for a workout"], createdAt: "1-5-2022" }];


const Home: NextPage = () => {
  const [activeTodoId, setActiveTodoId] = useState(todoLists[0].id);
  const [activeTodo, setActiveTodo] = useState(todoLists[0]);
  useEffect(() => {
    let todo = todoLists.filter((todo) => todo.id === activeTodoId)[0];
    if (todo.name) {
      setActiveTodo(todo);
    }
  }, [activeTodoId]);
  return (
    <div>
      <Head>
        <title>Next Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">

        {/* Section for showing todo lists */}
        <section className="flex flex-col w-2/12 border min-h-screen">
          <div className="flex items-center py-3 px-4">
            <Image src="/assets/user1.jpg" alt="icon" width="35" height="35" className="mr-4 rounded-full shadow-lg" />
            <p className="flex-1 font-medium">Awais</p>
            <Image src="/assets/search.png" width="22" height="22" alt="search-icon" className="cursor-pointer" />
          </div>
          <h1 className="font-medium ml-3 my-4">Your Lists</h1>
          {
            todoLists.map((obj: { id: number, todos: string[], name: string, createdAt: string }, i: number) => {
              return <div onClick={() => setActiveTodoId(obj.id)}
                className="flex items-center py-3 px-4 cursor-pointer transition hover:bg-gray-200" key={obj.id}>
                <Image src="/assets/todo1.png" alt="icon" width="25" height="25" className="mr-4" />
                <p className="flex-1">{obj.name}</p>
                <p>{obj.todos.length > 0 ? obj.todos.length : ""}</p>
              </div>
            })
          }
          <div className="flex items-center py-3 px-4 cursor-pointer hover:underline">
            <Image src="/assets/add.png" alt="icon" width="35" height="35" className="mr-2 rounded-full" />
            <p className="flex-1 font-medium">Add new list</p>
          </div>

        </section>
        {/* Section for showing todo items in each list */}
        <section className="p-12">
          <div>
            <h1 className="font-semibold text-3xl">{activeTodo.name}
            </h1>
            <p className="font-medium text-gray-400">{activeTodo.createdAt}</p>
          </div>
          <div className="mt-12">
            {activeTodo.todos.map((item: string, index: number) => {
              return <div key={index} className="flex items-center my-2">
                <Image src="/assets/unchecked.png" alt="unchecked-icon" width="25" height="25"
                  className="mx-3 cursor-pointer" />
                <p>{item}</p>
              </div>
            })}
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
